name: moduledetection_evaluation
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.*
  - fisher=0.1.*
  - jupytext=1.13.*
  - jupyter=1.0.*
  - matplotlib=3.4.*
  - numba=0.54.*
  - numpy=1.20.*
  - pandas=1.3.*
  - pip
  - python=3.9.*
  - seaborn=0.11.*
  - scikit-learn=0.24.*
  - scikit-learn-intelex=2021.*
  - scipy=1.7.*
  - statsmodels=0.12.*
  - pip:
    - git+https://github.com/jfrelinger/cython-munkres-wrapper
